    - name: nodejs_setup
      include_role: #we are calling that playbook by using include role
      name: common
      tasks_from: nodejs-setup

    - name: app_setup
      include_role:
        name: common
        tasks_from: app-setup

    - name: system_setup
      include_role:
        name: common
        tasks_from: systemd-setup